# -*- coding: utf-8 -*-
"""Boston.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ydGmaEwjMmuOnTIxfx9kABxsueUL5PLG
"""

import tensorflow as tf
import pandas as pd

src = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv"
data = pd.read_csv(src)

print(data)

data.head()

print(data.columns)

iv = data[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
dv = data[['medv']]

print(iv, dv)

print(iv.shape, dv.shape)

X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

model.fit(iv, dv, epochs=10)

model.predict(iv[0:5])

dv[0:5]

# 모델의 수식 확인
model.get_weights()

